# Generated by Django 5.0.6 on 2024-07-11 12:53

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room name')),
                ('slug', models.SlugField(help_text='Enter the name that you want to be appended to the link (e.g. chats/your_chat_slug)', unique=True, verbose_name='Link name')),
                ('password', chats.models.RoomPwdField()),
            ],
        ),
    ]
